name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile Tests
      run: g++ -o run_tests tests.cpp -I.
    - name: Run Tests
      run: ./run_tests
